# 1. Distribusi Binomial

Contoh aplikasi distribusi binomial di berbagai bidang

### 1.1 Lemparan Koin
- Konteks: Melakukan lemparan koin sebanyak n kali dan menghitung jumlah munculnya kepala.
- Penerapan: Misalnya P(X=k) adalah probabilitas mendapatkan tepat k kepala dalam n lemparan.

### 2.1 Ujian Pilihan Ganda
- Konteks: Seorang siswa menebak jawaban pada ujian pilihan ganda yang memiliki n pertanyaan dan ingin tahu probabilitas menebak benar k jawaban tanpa membaca materi.
- Penerapan: Menggunakan distribusi binomial, kita bisa menghitung P(X=k), probabilitas menebak benar k jawaban dari n pertanyaan dengan masing-masing memiliki peluang penebakan benar p.
### 3.1 Kontrol Kualitas Produk
- Konteks: Dalam inspeksi kualitas, seorang inspektur mengambil sampel n produk dan memeriksa berapa banyak di antaranya yang cacat.
- Penerapan: Jika kita tahu probabilitas sebuah produk adalah cacat (misalkan p), kita bisa menggunakan distribusi binomial untuk menghitung probabilitas bahwa tepat k dari n produk yang diperiksa akan cacat.

### 4.1 Pemilihan Acak
- Konteks: Dalam sebuah kelompok dari N orang, kita memilih n orang secara acak dan kita ingin tahu peluang bahwa k dari mereka memiliki karakteristik tertentu (misalnya, golongan darah tertentu).
- Penerapan: Jika kita tahu p, probabilitas seorang individu acak memiliki karakteristik tersebut, kita bisa gunakan distribusi binomial untuk menghitung P(X=k).

### 5.1 Biologi dan Penelitian Kesehatan
- Konteks: Melakukan n eksperimen laboratorium dan mencatat kemunculan suatu kejadian (misal, reaksi terhadap obat).
- Penerapan: Jika kita tahu p, probabilitas kejadian tersebut dalam satu eksperimen, kita bisa menggunakan distribusi binomial untuk menghitung peluang terjadinya kejadian tersebut k kali dalam  n eksperimen.

### 6.1 Pemasaran
- Konteks: Seorang pemasar mengirimkan n email promosi dan tertarik untuk mengetahui probabilitas mendapatkan k respons.
- Penerapan: Jika diketahui bahwa probabilitas mendapatkan respons dari satu email adalah p, maka probabilitas mendapatkan k respons dari n email dapat dihitung dengan distribusi binomial.



Keseluruhan contoh di atas mencerminkan bagaimana distribusi binomial dapat diterapkan dalam berbagai konteks di kehidupan sehari-hari, mencakup beragam bidang seperti statistik, ekonomi, biologi, psikologi, dan banyak lagi.

# 2. Generate data

Bagaimana cara membangkitkan data yang berdistribusi binomial ?

In [1]:
import numpy as np
from scipy.stats import binom

- scipy.stats.binom.pmf(k, n, p, loc=0)
- scipy.stats.binom.cdf(k, n, p, loc=0)
- scipy.stats.binom.ppf(q, n, p, loc=0)
- scipy.stats.binom.rvs(n, p, loc=0, size=1)

In [2]:
"""
Bagaimana jika peluang = 1 ?

Menunjukkan bahwa terdapat 10 kali keberhasilan dalam 10 kali percobaan. Misal peluang 
mendapatkan bilangan bulat pada dadu normal.

"""
np.random.binomial(10, 1, 50)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [3]:
"""
Bagaimana jika peluang = 0 ?

Menunjukkan bahwa tidak ada keberhasilan dalam 10 kali percobaan tersebut, karena peluang = 0.
Misal peluang mendapatkan angka 7 pada dadu normal.
"""
np.random.binomial(10, 0, 50)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [4]:
"""
Hal ini menunjukkan bahwa s[0] = 6, artinya ada 2 keberhasilan dalam 10 kali percobaan.
Misal peluang mendapatkan angka 4 pada dadu normal.
"""
s = np.random.binomial(n=10, p=0.5, size = 50)
s

array([1, 6, 5, 5, 6, 4, 5, 3, 6, 3, 1, 6, 7, 2, 5, 5, 7, 5, 2, 2, 5, 6,
       4, 5, 3, 7, 5, 6, 3, 2, 3, 6, 5, 4, 4, 5, 3, 7, 6, 3, 7, 8, 5, 4,
       7, 4, 6, 5, 3, 9])

# 3. Graph

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
x = random.binomial(n=10, p=0.5, size=1000)

In [8]:
sns.distplot(x, hist=True, kde=False)

plt.show()

# 4. Case

Case:

Seorang produsen mobil mengklaim bahwa tidak lebih dari 10% mobil mereka yang tidak aman. 15 mobil diperiksa untuk keselamatan, dan 3 di antaranya ditemukan tidak aman. Uji klaim produsen tersebut

### 4.1 Uji Hipotesis

Uji Hipotesis dengan tingkat kesalahan 5% (0.05)

- H0 : p <= 10% (proporsi mobil yang tidak aman)
- H1 : p > 10% (proporsi mobil yang aman)

In [9]:
from scipy.stats import binom_test

In [10]:
# Data
n_unsafe = 3  # Jumlah mobil yang tidak aman
n_total = 15  # Jumlah total mobil yang diperiksa
claimed_p = 0.10  # Klaim proporsi mobil yang tidak aman

# Melakukan uji binomial
# 'greater' mengindikasikan kita menguji apakah proporsi sebenarnya lebih besar dari klaim
p_value = binom_test(x=3, n=15, p=0.10, alternative='greater')

# Menampilkan hasil
print(f"p-value: {p_value}")


p-value: 0.18406106910639106


### 4.2 Kesimpulan

Karena pvalue (0.18) > 5% (0.05) maka tolak H0, sehingga dapat dikatakan klaim perusahaan tersebut terbukti

## Reference

- https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom_test.html